spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///moneysys

mybatis-plus:
  configuration:
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false #数据库下划线自动转换为驼峰
  mapper-locations: classpath:mapper/*Mapper.xml #mapper 映射文件

logging:
  file:
    path: /data/moneysys/log/
  level:
    root: info


